import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const add=async(page:Page,name:string)=>{await page.getByRole('button',{name:'Add element'}).click();await page.getByRole('menuitem',{name,exact:true}).click();};
const save=async(page:Page)=>{const event=page.waitForEvent('download');await page.getByRole('button',{name:'Save',exact:true}).click();const file=(await (await event).path())!;return {file,project:JSON.parse(await readFile(file,'utf8'))};};
const set=async(page:Page,label:string,value:string)=>{await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel(label,{exact:true}).press('Tab');};

test('welcome, blank project, explicit data bindings, unfinished save/open, and export',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('heading',{name:'New project',exact:true})).toBeVisible();await expect(page.getByTestId('vega-render')).toHaveCount(0);
  await page.getByLabel('Project name',{exact:true}).fill('Pipeline capacity');await page.getByRole('button',{name:'Create project'}).click();await expect(page.getByText('No layers yet')).toBeVisible();
  const blank=await save(page);expect(blank.project.elements).toEqual([]);expect(blank.project.sources[0].rows).toEqual([]);
  await add(page,'Horizontal bar chart');await expect(page.getByTestId('chart-setup')).toContainText('Add data');await expect(page.getByLabel('Category field',{exact:true})).toHaveValue('');await expect(page.getByLabel('Numeric value field',{exact:true})).toHaveValue('');
  await page.getByRole('button',{name:'Export Vega'}).click();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Finish chart setup');await expect(page.getByRole('button',{name:'Copy JSON'})).toBeDisabled();await expect(page.getByRole('button',{name:'Download JSON'})).toBeDisabled();await page.getByRole('button',{name:'Close dialog'}).click();
  const incomplete=await save(page);expect(incomplete.project.sources[0].rows).toEqual([]);await page.getByLabel('Open project file').setInputFiles(incomplete.file);await expect(page.getByTestId('chart-setup')).toBeVisible();
  await page.getByRole('button',{name:'Sample data',exact:false}).click();await expect(page.getByLabel('Sample data JSON')).toHaveValue('[]');await page.getByLabel('Sample data JSON').fill('[{"queue":"Alpha","percent":25},{"queue":"Beta","percent":90}]');await page.getByRole('button',{name:'Apply data'}).click();
  await page.getByRole('button',{name:'Bar chart',exact:true}).click();await page.getByLabel('Category field',{exact:true}).selectOption('queue');await expect(page.getByTestId('chart-setup')).toBeVisible();await page.getByLabel('Numeric value field',{exact:true}).selectOption('percent');await expect(page.getByTestId('chart-setup')).toHaveCount(0);await expect(page.getByTestId('vega-render')).toContainText('Alpha');
  await page.getByRole('button',{name:'Export Vega'}).click();await expect(page.getByRole('status')).toContainText('Valid Vega');const spec=JSON.parse(await page.getByLabel('Generated Vega JSON').inputValue());expect(spec.data[0].values).toEqual([{queue:'Alpha',percent:25},{queue:'Beta',percent:90}]);expect(errors).toEqual([]);
});

test('color selection keeps draft local; apply is one undo, cancel and invalid input preserve the document',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:'Create project'}).click();await add(page,'Rectangle');
  await page.getByRole('button',{name:'Fill',exact:true}).click();const picker=page.getByRole('dialog',{name:'Fill color picker'});const plane=await page.getByRole('slider',{name:'Saturation and brightness'}).boundingBox();await page.mouse.move(plane!.x+10,plane!.y+10);await page.mouse.down();await page.mouse.move(plane!.x+140,plane!.y+80,{steps:12});await page.mouse.up();await expect(picker).toBeVisible();await expect(page.getByTestId('vega-render').locator('path[fill="#5965dd"]')).toHaveCount(1);
  await page.getByLabel('Hex color').fill('#nope');await expect(page.getByRole('button',{name:'Apply color'})).toBeDisabled();await expect(picker.getByRole('alert')).toContainText('six-digit');await page.getByLabel('Hex color').fill('#123456');await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('button',{name:'Fill',exact:true})).toContainText('#5965DD');
  await page.getByRole('button',{name:'Fill',exact:true}).click();await page.getByLabel('Hex color').fill('#123456');await page.getByRole('button',{name:'Apply color'}).click();await expect(page.getByRole('button',{name:'Fill',exact:true})).toContainText('#123456');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByRole('button',{name:'Fill',exact:true})).toContainText('#5965DD');await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.getByRole('button',{name:'Fill',exact:true})).toContainText('#123456');
  await page.getByRole('button',{name:'Fill',exact:true}).click();await page.getByRole('slider',{name:'Saturation and brightness'}).focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Fill',exact:true})).toContainText('#123456');
});

test('groups preserve child positions, inherit locks and visibility, and round trip through files',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:'Open example',exact:false}).click();await page.getByRole('button',{name:'Panel title',exact:true}).click();await page.getByRole('button',{name:'Description',exact:true}).click({modifiers:['Shift']});await page.getByRole('button',{name:'Group selection',exact:true}).click();await set(page,'Layer name','Heading');
  const grouped=await save(page);const group=grouped.project.elements.find((e:{type:string})=>e.type==='group');expect(grouped.project.elements.filter((e:{parentId:string})=>e.parentId===group.id)).toHaveLength(2);
  const initialX=await page.getByLabel('X',{exact:true}).inputValue(),box=await page.getByTestId(`overlay-${group.id}`).boundingBox();await page.mouse.move(box!.x+40,box!.y+30);await page.mouse.down();await page.mouse.move(box!.x+85,box!.y+55,{steps:10});await page.mouse.up();await expect(page.getByLabel('X',{exact:true})).not.toHaveValue(initialX);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByLabel('X',{exact:true})).toHaveValue(initialX);
  await page.getByRole('button',{name:'Collapse Heading',exact:true}).click();await expect(page.getByRole('button',{name:'Panel title',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Expand Heading',exact:true}).click();await expect(page.getByRole('button',{name:'Panel title',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Lock Heading',exact:true}).click();await page.getByRole('button',{name:'Panel title',exact:true}).click();await expect(page.getByLabel('X',{exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Lock Panel title',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Unlock Heading',exact:true}).click();
  await page.getByRole('button',{name:'Hide Heading',exact:true}).click();await expect(page.getByTestId('vega-render')).not.toContainText('Logstash queue usage');await page.getByRole('button',{name:'Show Heading',exact:true}).click();
  await page.getByRole('button',{name:'Queue usage',exact:true}).click();await page.getByLabel('Move to group').selectOption(group.id);await page.getByLabel('Move to group').selectOption('');await expect(page.getByLabel('X',{exact:true})).toHaveValue('40');
  await page.getByRole('button',{name:'Heading',exact:true}).click();await page.getByRole('button',{name:'Duplicate',exact:true}).click();await expect(page.getByRole('button',{name:'Heading copy',exact:true})).toBeVisible();await page.getByRole('button',{name:'Delete layer',exact:true}).click();await expect(page.getByRole('button',{name:'Heading copy',exact:true})).toHaveCount(0);
  const result=await save(page);await page.getByLabel('Open project file').setInputFiles(result.file);const restored=await save(page);expect(restored.project).toEqual(result.project);
  await page.getByRole('button',{name:'Heading',exact:true}).click();await page.getByRole('button',{name:'Ungroup',exact:true}).click();await expect(page.getByRole('button',{name:'Heading',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Panel title',exact:true}).click();await expect(page.getByLabel('X',{exact:true})).toHaveValue('40');
});

test('both themes cover welcome, editor and color picker without changing exported design',async({page},testInfo)=>{
  await page.goto('/');await page.screenshot({path:testInfo.outputPath('welcome-dark.png'),fullPage:true});await page.getByRole('button',{name:'Switch to light mode'}).click();await page.screenshot({path:testInfo.outputPath('welcome-light.png'),fullPage:true});await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','light');
  await page.getByRole('button',{name:'Open example',exact:false}).click();await page.getByRole('button',{name:'Queue usage',exact:true}).click();await page.screenshot({path:testInfo.outputPath('editor-light.png'),fullPage:true});await page.getByRole('button',{name:'Bar color',exact:true}).click();await page.screenshot({path:testInfo.outputPath('picker-light.png'),fullPage:true});await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.getByRole('button',{name:'Export Vega'}).click();const before=await page.getByLabel('Generated Vega JSON').inputValue();await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('button',{name:'Switch to dark mode'}).click();await page.screenshot({path:testInfo.outputPath('editor-dark.png'),fullPage:true});await page.getByRole('button',{name:'Bar color',exact:true}).click();await page.screenshot({path:testInfo.outputPath('picker-dark.png'),fullPage:true});await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Export Vega'}).click();await expect(page.getByLabel('Generated Vega JSON')).toHaveValue(before);
});

test('unsaved-work protection and invalid files preserve the current project',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:'Create project'}).click();await add(page,'Text');await expect(page.getByLabel('Unsaved changes',{exact:true})).toBeVisible();
  page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:'Home',exact:true}).click();await expect(page.getByRole('button',{name:'Text',exact:true})).toBeVisible();
  await page.getByLabel('Open project file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":50}')});await expect(page.getByRole('alert')).toContainText('Unsupported');await expect(page.getByRole('button',{name:'Text',exact:true})).toBeVisible();
  page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'New',exact:true}).click();await expect(page.getByRole('button',{name:'Create project'})).toBeVisible();await page.getByRole('button',{name:'Create project'}).click();await expect(page.getByText('No layers yet')).toBeVisible();
});
