import {afterEach,describe,it,expect,vi} from 'vitest';
import {useEditor} from '../src/store';
import {blankProject,newElement,type Project} from '../src/model';
import {groupLayers,align,reparent,ungroup,duplicateLayers,removeLayers,reorder} from '../src/commands';
import {bounds,worldPosition,ordered} from '../src/hierarchy';
import {hsvToHex,hexToHsv,validHex,isLightColor} from '../src/color';
import {compile} from '../src/compiler';
afterEach(()=>vi.unstubAllGlobals());
describe('color fidelity',()=>{
 it.each(['#ff0000','#ffff00','#00ff00','#00ffff','#0000ff','#ff00ff','#000000','#ffffff','#5965dd','#888888'])('round trips %s through visual picker coordinates',hex=>{expect(hsvToHex(...hexToHsv(hex))).toBe(hex);});
 it('rejects invalid colors and distinguishes document contrast',()=>{expect(validHex('#abc')).toBe(false);expect(validHex('#123xyz')).toBe(false);expect(validHex('#AaBbCc')).toBe(true);expect(isLightColor('#ffffff')).toBe(true);expect(isLightColor('#171c27')).toBe(false);});
});
describe('group bounds and editor transactions',()=>{
 const fixture=():Project=>({...blankProject(),elements:[{...newElement('rectangle'),id:'a',x:100,y:100,width:200,height:100},{...newElement('text'),id:'b',x:350,y:220,width:300,height:40}]});
 it('bounds contain the children, alignment uses visual edges, and empty groups have a selectable frame',()=>{const g=groupLayers(fixture(),['a','b']);const element=g.project.elements.find(e=>e.id===g.id)!;expect(bounds(g.project,element)).toEqual({x:100,y:100,width:550,height:160});for(const [side,x] of [[0,0],[1,175],[2,350]]){const p=align(g.project,element,side);expect(bounds(p,p.elements.find(e=>e.id===g.id)!)).toMatchObject({x});}const empty=groupLayers(blankProject(),[]);expect(bounds(empty.project,empty.project.elements[0]).width).toBe(40);});
 it('makes a complete group gesture one command and preserves local child coordinates across undo/redo',()=>{const g=groupLayers(fixture(),['a','b']);const s=useEditor.getState();s.open({...g.project,elements:ordered(g.project)});const original=structuredClone(useEditor.getState().project);s.edit(g.id,{x:200,y:300});expect(useEditor.getState().past).toHaveLength(1);expect(useEditor.getState().project.elements.find(e=>e.id==='a')!.x).toBe(0);s.undo();expect(useEditor.getState().project).toEqual(original);s.redo();const p=useEditor.getState().project;expect(worldPosition(p,p.elements.find(e=>e.id==='a')!)).toEqual({x:200,y:300});});
 it('cannot bypass inherited locks or move a group containing a locked child',()=>{const g=groupLayers(fixture(),['a','b']);const s=useEditor.getState();s.open(g.project);s.edit('a',{locked:true});s.edit(g.id,{x:400});expect(useEditor.getState().project.elements.find(e=>e.id===g.id)!.x).toBe(100);s.edit(g.id,{locked:true});s.edit('a',{locked:false});expect(useEditor.getState().project.elements.find(e=>e.id==='a')!.locked).toBe(true);});
 it('keeps selection, collapse and theme changes outside document history and export',()=>{const s=useEditor.getState();s.open(fixture());const spec=compile(useEditor.getState().project);s.select('a');s.select('b',true);expect(useEditor.getState().selection).toEqual(['a','b']);s.select('a',true);expect(useEditor.getState().selection).toEqual(['b']);s.selectMany([]);expect(useEditor.getState().selected).toBeNull();s.selectMany(['a']);s.toggleCollapsed('a');s.toggleCollapsed('a');expect(useEditor.getState().collapsed).toEqual([]);const setItem=vi.fn();vi.stubGlobal('localStorage',{setItem});s.setTheme('light');expect(setItem).toHaveBeenCalledWith('vega-studio-theme','light');s.setScreen('welcome');expect(useEditor.getState().screen).toBe('welcome');expect(compile(useEditor.getState().project)).toEqual(spec);expect(useEditor.getState().past).toHaveLength(0);vi.stubGlobal('localStorage',{setItem:()=>{throw Error('unavailable');}});s.setTheme('dark');expect(useEditor.getState().theme).toBe('dark');});
 it('rejects invalid destinations and cross-parent grouping before modifying any data',()=>{const g=groupLayers(fixture(),['a']);expect(()=>groupLayers(g.project,['a','b'])).toThrow('same group');expect(()=>reparent(g.project,['b'],'missing')).toThrow('valid destination');expect(()=>reparent(g.project,['b'],'a')).toThrow('valid destination');const p={...g.project,elements:g.project.elements.map(e=>e.id===g.id?{...e,locked:true}:e)};expect(()=>reparent(p,['b'],g.id)).toThrow('destination');expect(()=>reparent(p,['a'],null)).toThrow('Unlock');expect(()=>groupLayers(p,['a'])).toThrow('Unlock');expect(ungroup(p,'b')).toEqual(p);expect(reorder(p,'missing',1)).toEqual(p);expect(reorder(p,'b',1)).toEqual(p);expect(duplicateLayers(blankProject(),[]).project).toEqual(blankProject());expect(removeLayers(blankProject(),[])).toEqual(blankProject());});
});
