import { readFile, readdir, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";

// Include all installed, non-optional production packages, even when tree-shaken.
// Optional native build tools are not redistributed in the browser application.
const lock = JSON.parse(await readFile("package-lock.json", "utf8"));
const fallback = {
  "react-remove-scroll-bar": {
    path: "docs/licenses/react-remove-scroll-bar.txt",
    source: "https://github.com/theKashey/react-remove-scroll-bar/blob/7301c160fda44cb8cf2b9fdfde61efad35736196/LICENSE",
  },
};
let output = `# Third-party notices

Generated by \`npm run notices\` from locked production dependencies.
These packages retain their own licenses, independently of Vega Studio's MIT
license. Full shipped license/notice files follow, including icon attribution.
Development tools are not part of the browser distribution; their licenses
remain in their installed packages. Keep this file with distributed builds.
No Kibana source or datasets are bundled; examples are synthetic.

`;
for (const [directory, entry] of Object.entries(lock.packages).sort()) {
  if (!directory || entry.dev || entry.optional) continue;
  const pkg = JSON.parse(await readFile(join(directory, "package.json"), "utf8"));
  if (pkg.version !== entry.version) throw new Error(`Run npm ci: ${pkg.name}`);
  const files = [];
  for (const name of (await readdir(directory)).sort()) {
    if (/^(licen[cs]e|copying|notice)([.-]|$)/i.test(name) &&
        (await stat(join(directory, name))).isFile()) files.push(name);
  }
  output += `## ${pkg.name} ${pkg.version}\n\nDeclared license: ${pkg.license ?? entry.license ?? "See text below"}\n\n`;
  if (files.length) {
    for (const name of files) {
      const text = (await readFile(join(directory, name), "utf8")).replace(/\r\n/g, "\n").trim();
      output += `### ${name}\n\n\`\`\`text\n${text}\n\`\`\`\n\n`;
    }
  } else {
    const item = fallback[pkg.name];
    if (!item) throw new Error(`Missing license text for ${pkg.name}`);
    const text = (await readFile(item.path, "utf8")).replace(/\r\n/g, "\n").trim();
    output += `License omitted from npm package; retained from [upstream's license addition](${item.source}). The installed package declares MIT.\n\n\`\`\`text\n${text}\n\`\`\`\n\n`;
  }
}
await writeFile("THIRD_PARTY_NOTICES.md", output);
